version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "crdant"
    assignees:
      - "crdant"
    open-pull-requests-limit: 5
    groups:
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "crdant"
    assignees:
      - "crdant"