version: "2"
run:
  go: "1.23"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: Use structured logging with slog instead
    dupl:
      threshold: 100
    errorlint:
      errorf: true
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - gocyclo
          - mnd
        path: _test\.go
      - linters:
          - gochecknoinits
        path: cmd/
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print.*|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: (possible misuse of unsafe.Pointer|should have signature)
      - path: (.+)\.go$
        text: ineffective break statement. Did you mean to break out of the outer loop
      - path: (.+)\.go$
        text: (G103|G307|G204|G104)
      - path: (.+)\.go$
        text: (G103|G307)
      - linters:
          - dupl
        path: pkg/mcp/tools\.go$
        text: "lines are duplicate"
      - linters:
          - unparam
        path: pkg/mcp/server\.go$
        text: "registerTools.*result 0.*is always nil|registerResources.*result 0.*is always nil"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
severity:
  default: error
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/crdant/replicated-mcp-server
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
